<a href="https://colab.research.google.com/github/sophia1kucan/Next.js/blob/main/Matrix_calculations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
Row = int(input("Enter the number of rows:"))
Column = int(input("Enter the number of columns:"))

matrix = []
print("Enter the entries row wise:")


for row in range(Row):
    a = []
    for column in range(Column):
        a.append(int(input()))
    matrix.append(a)

for row in range(Row):
    for column in range(Column):
        print(matrix[row][column], end=" ")
    print()


Enter the number of rows:3
Enter the number of columns:3
Enter the entries row wise:
4
-2
4
0
4
-2
6
0
4
4 -2 4 
0 4 -2 
6 0 4 


In [13]:
import numpy as np

X = np.array([[4, -2, 4], [0, 4, -2], [6, 0, 4]])

print(X)




if np.linalg.det(X) != 0:
    X_inv = np.linalg.inv(X)
else:
    print("Inverse doesn't exist")

print(np.linalg.inv(X))







[[ 4 -2  4]
 [ 0  4 -2]
 [ 6  0  4]]
[[-2.  -1.   1.5]
 [ 1.5  1.  -1. ]
 [ 3.   1.5 -2. ]]
